# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - wie-dev

on:
  push:
    branches:
      - release-dev

jobs:
  build-client:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@master

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: NPM install client
      run: npm install
      working-directory: ./react-front

    - name: NPM run tests
      run: npm run test
      working-directory: ./react-front

    - name: Run client build
      run: npm run build
      env:
        CI: false
      working-directory: ./react-front

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: react-front/build
        # retention-days: 5

  build-client-and-deploy-server:
    needs: build-client
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@master
      
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: ls before
      run: ls

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: NPM install server
      run: npm install

    #- name: Copy build folder
    #  run: npm run copy-build-folder

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: build 
        path: build/  
        
    - name: ls after
      run: ls
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wie-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fe210901a08f480983681aed107819be }}
        package: .